/* Only the icons that are used in the project should be included in this index.
This will result in proper tree-shaking reducing the bundle size of the application */

export {
  Plus as PlusIcon,
  Minus as MinusIcon,
  X as CloseIcon,
  XCircle as CloseCircleIcon,
  Clock as ClockIcon,
  Check as CheckIcon,
  CheckCheck as CheckCheckIcon,
  Minimize2 as MinimizeIcon,
  Maximize2 as MaximizeIcon,
  ChevronUp as ChevronUpIcon,
  ChevronDown as ChevronDownIcon,
  ChevronDownCircle as ChevronDownCircleIcon,
  ChevronLeft as ChevronLeftIcon,
  ChevronsLeft as ChevronsLeftIcon,
  ChevronRight as ChevronRightIcon,
  ChevronsRight as ChevronsRightIcon,
  MoreHorizontal as MoreHorizontalIcon,
  Settings as SettingsIcon,
  Search as SearchIcon,
  Trash as TrashIcon,
  Trash2 as Trash2Icon,
  Image as ImageIcon,
  FileText as FileTextIcon,
  Send as SendIcon,
  Users as UsersIcon,
  Home as HomeIcon,
  Box as BoxIcon,
  Award as AwardIcon,
  Square as SquareIcon,
  CheckSquare as CheckSquareIcon,
  ClipboardCheck as ClipboardCheckIcon,
  MoreVertical as MoreVerticalIcon,
  Bell as BellIcon,
  ExternalLink as ExternalIcon,
  Inbox as InboxIcon,
  Filter as FilterIcon,
  PlusCircle as PlusCircleIcon,
  ArrowLeft as ArrowLeftIcon,
  ArrowRight as ArrowRightIcon,
  MoveUp as MoveUpIcon,
  MoveDown as MoveDownIcon,
  Wallet as WalletIcon,
  Calendar as CalendarIcon,
  Forward as ForwardIcon,
  CircleDashed as CircleDashedIcon,
  CheckCircle2 as CheckCircle2Icon,
  CircleDot as CircleDotIcon,
  PenLine as PenLineIcon,
  SquarePen as SquarePenIcon,
  Upload as UploadIcon,
  Download as DownloadIcon,
  File as FileIcon,
  AlertCircle as AlertCircleIcon,
  Dot as DotIcon,
  Info as InfoIcon,
  AlertTriangle as AlertTriangleIcon,
  AlertOctagon as AlertOctagonIcon,
  Eye as EyeIcon,
  EyeOff as EyeOffIcon,
  FileWarning as FileWarningIcon,
  ShoppingCart as ShoppingCartIcon,
  Pencil as PencilIcon,
  // ChartArea,
  Film as FilmIcon,
  RefreshCw as Sync,
  RefreshCwOff as SyncOff,
  RotateCw as Rotate,
  ChartNetwork as ChartNetworkIcon,
  ScrollText as ScrollTextIcon,
  DatabaseZapIcon as DatabaseZapIcon,
  Menu as MenuIcon,
  CloudUploadIcon as CloudUploadIcon,
  ArrowUp,
  Copy as CopyIcon,
  BotMessageSquare as BotMessageSquareIcon,
  ThumbsUp,
  ThumbsDown,
  LockIcon,
  Bookmark as Bookmark,
  PanelLeft as PanelLeft,
  Bot as BotIcon,
  EllipsisVertical as MoreVertical,
  Ellipsis,
  CircleDotDashed as DotDashedCircle,
  Landmark,
  AppWindow,
  BookUser,
  Tent,
  Blend,
  CopyPlus,
  DiamondPlus,
  MapPin,
  PackageSearch,
  ImagePlay,
  RocketIcon,
  ArrowRight,
  ChevronsDown,
  ImagePlus,
  GripVertical as GripVerticalIcon,
  PanelLeft as PanelLeftIcon,
  PlayIcon as PlayIcon,
  EditIcon,
  HouseIcon,
  MessagesSquare,
  RotateCwSquare,
  Minimize2,
  Facebook,
  Instagram,
  Twitter,
  Linkedin,
  Youtube,
  Loader2
} from 'lucide-react';
