import {
  SelectProps,
  SelectChangeEvent,
  TextFieldProps,
  FormControlLabelProps,
  AutocompleteProps,
  AutocompleteRenderOptionState,
  RadioGroupProps,
  SwitchProps,
  TabProps,
  TooltipProps,
  useMediaQuery,
} from '@mui/material';

export {
  Dialog,
  Grid,
  Grow,
  Tabs,
  Tab,
  Avatar,
  Button,
  Checkbox,
  IconButton,
  InputAdornment,
  Stack,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableSortLabel,
  TableHead,
  TableRow,
  TextField,
  Divider,
  InputLabel,
  Radio,
  RadioGroup,
  FormControlLabel,
  Accordion,
  AccordionSummary,
  AccordionDetails,
  Autocomplete,
  List,
  ListItemButton,
  ListItem,
  Select,
  Stepper,
  Step,
  Box,
  MenuItem,
  OutlinedInput,
  Chip,
  Paper,
  Pagination,
  Snackbar,
  Breadcrumbs,
  Drawer,
  Menu,
  FormControl,
  FormHelperText,
  FormLabel,
  Popper,
  Skeleton,
  Alert,
  Switch,
  Tooltip,
  ButtonGroup,
  Popover,
  CircularProgress,
  ClickAwayListener,
  PaginationItem,
  MobileStepper,
  useMediaQuery,
} from '@mui/material';

export type {
  SelectProps,
  SelectChangeEvent,
  FormControlLabelProps,
  AutocompleteProps,
  AutocompleteRenderOptionState,
  TextFieldProps,
  RadioGroupProps,
  SwitchProps,
  TabProps,
  TooltipProps,
};

export const isMobileView = () => useMediaQuery(`(min-width: 320px) and (max-width: 767px)`);