export const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_SET_USER = 'AUTH_SET_USER';
export const AUTH_CLEAR_ERROR = 'AUTH_CLEAR_ERROR';
export const AUTH_FORGOT_PASSWORD_REQUEST = 'AUTH_FORGOT_PASSWORD_REQUEST';
export const AUTH_FORGOT_PASSWORD_SUCCESS = 'AUTH_FORGOT_PASSWORD_SUCCESS';
export const AUTH_FORGOT_PASSWORD_FAILURE = 'AUTH_FORGOT_PASSWORD_FAILURE';
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const SET_SIDEBAR_OPEN = 'SET_SIDEBAR_OPEN';
export const TOGGLE_NOTIFICATION_DRAWER = 'TOGGLE_NOTIFICATION_DRAWER';
export const SET_NOTIFICATION_DRAWER_OPEN = 'SET_NOTIFICATION_DRAWER_OPEN';

// Dashboard-derived slices
export const RECENT_ACTIVITY_FETCH_REQUEST = 'RECENT_ACTIVITY_FETCH_REQUEST';
export const RECENT_ACTIVITY_FETCH_SUCCESS = 'RECENT_ACTIVITY_FETCH_SUCCESS';
export const RECENT_ACTIVITY_FETCH_FAILURE = 'RECENT_ACTIVITY_FETCH_FAILURE';

export const UPCOMING_SCHEDULES_FETCH_REQUEST = 'UPCOMING_SCHEDULES_FETCH_REQUEST';
export const UPCOMING_SCHEDULES_FETCH_SUCCESS = 'UPCOMING_SCHEDULES_FETCH_SUCCESS';
export const UPCOMING_SCHEDULES_FETCH_FAILURE = 'UPCOMING_SCHEDULES_FETCH_FAILURE';
export const SET_UPCOMING_SCHEDULES = 'SET_UPCOMING_SCHEDULES';
